@startuml
' Questões:
'  entregas parciais: entregas e linhas de entrega

class Produto {
    PK id: Number
    nome: String
    dataRegisto: Date
    descricao: String
    ' Questão: 10% de desconto em informática? ou iPhone 14 com desconto?
    desconto: Number
    stock: Number
    peso: Number
}

class Preco {
    PK id: Number
    dataInicio: Date
    dataFim: Date
    valor: Number
}

class Categoria {
    PK id: Number
    nome: String
    descricao: String
}

class Utilizador {
    PK id: Number
    nome: String
    dataNascimento: Date
    email: String
    telefone: String
    username: String
    password: String
    ' Questão: contactos?
    '  1) email e telefone (2 contactos)
    '  2) email1, email2, telefone1, telefone2, batata1, ... (n contactos)   
}

class Cliente {
    PK FK utilizador: Utilizador
    moradaEntrega: String
}

class Funcionario {
    PK FK utilizador: Utilizador
}

class Encomenda {
    PK id: Number
    ' Questão: valorExpedição e/ou valorTotal?
    valorExpedicao: Number
    valorTotal: Number
    dataCriacao: Date
}

class LinhaEncomenda {
    PK FK encomenda: Encomenda
    PK FK produto: Produto
    quantidade: Number
    ' No caso do preço do produto mudar,
    ' o preço da linha de encomenda mantém-se
    preco: Number
}

' Aberto, Aceite, Cancelado
class EstadoEncomenda {
    PK id: Number
    nome: String
    data: Date
}

class Segmento {
    PK id: Number
    nome: String
}

class PrioridadeEncomenda {
    PK id: Number
    nome: String
}

class Entrega {
    PK id: Number
    modo: String
    data: Date
}

class LinhaEntrega {
    PK FK entrega: Entrega
    PK FK linhaEncomenda: LinhaEncomenda
    quantidade: Number
}

class Devolucao {
    PK FK id: Number
    motivo: String
    data: Date
    valor: Number
}

class Pagamento {
    PK FK encomenda: Encomenda
}

class EstadoPagamento {
    PK id: Number
    nome: String
}

class TipoEmbalagem {
    PK id: Number
    nome: String
}

class Zona {
    PK id: Number
    nome: String
}

class Estado {
    PK id: Number
    nome: String
}

class Cidade {
    PK id: Number
    nome: String
}

Cidade "0..*" - "1" Estado
Estado "0..*" - "1" Zona
Zona "*" - "1" Funcionario

Categoria "1" -- "*" Categoria : subCategorias

Encomenda "1" -- "1..*" LinhaEncomenda
Produto "1" - "*" LinhaEncomenda

Categoria "1" -- "1..*" Produto

Devolucao "0..1" - "1" Encomenda
TipoEmbalagem "1" -- "*" Encomenda

Utilizador "1" -- "1" Funcionario
Utilizador "1" -- "1" Cliente

Funcionario "1" -- "*" Encomenda
Cliente "1" -- "*" Encomenda

Encomenda "1" -- "1" Pagamento
Pagamento "1" -- "*" EstadoPagamento

Cliente "*" - "1" Segmento

Produto "1" -- "*" Preco

Encomenda "1" -- "*" Entrega
LinhaEntrega "*" - "1" Entrega
LinhaEncomenda "1" -- "*" LinhaEntrega

Encomenda "1" -- "*" EstadoEncomenda
Encomenda "*" -- "1" PrioridadeEncomenda
@enduml